# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Goodies Bandit
tagline:          'Lose inches all over!'
description:      'Eat Clean! The #1 plan for super health and real weight loss'
url:              http://blog.goodiesbandit.com

author:
  name:           'Goodies Bandit'

paginate:         5

# Custom vars
version:          2.0.0