# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Goodies Bandit
tagline:          'A Jekyll theme'
description:      'Stealing food from you for your own good'
url:              http://blog.goodiesbandit.com

author:
  name:           'Goodies Bandit'

paginate:         5

# Custom vars
version:          2.0.0